// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatikaSurvivor.Context;

#nullable disable

namespace PatikaSurvivor.Migrations
{
    [DbContext(typeof(SurvivorDbContext))]
    partial class SurvivorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PatikaSurvivor.Entities.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 10, 10, 46, 42, 475, DateTimeKind.Local).AddTicks(1286),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 10, 10, 10, 46, 42, 475, DateTimeKind.Local).AddTicks(1268),
                            Name = "Ünlüler"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 10, 10, 10, 46, 42, 475, DateTimeKind.Local).AddTicks(1290),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2024, 10, 10, 10, 46, 42, 475, DateTimeKind.Local).AddTicks(1290),
                            Name = "Gönüllüler"
                        });
                });

            modelBuilder.Entity("PatikaSurvivor.Entities.CompetitorEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Competitors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 10, 10, 10, 46, 42, 475, DateTimeKind.Local).AddTicks(1397),
                            FirstName = "Acun",
                            IsDeleted = false,
                            LastName = "Ilıcalı",
                            ModifiedDate = new DateTime(2024, 10, 10, 10, 46, 42, 475, DateTimeKind.Local).AddTicks(1396)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 10, 10, 10, 46, 42, 475, DateTimeKind.Local).AddTicks(1399),
                            FirstName = "Fatih",
                            IsDeleted = false,
                            LastName = "Terim",
                            ModifiedDate = new DateTime(2024, 10, 10, 10, 46, 42, 475, DateTimeKind.Local).AddTicks(1399)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 10, 10, 10, 46, 42, 475, DateTimeKind.Local).AddTicks(1401),
                            FirstName = "Sezen",
                            IsDeleted = false,
                            LastName = "Aksu",
                            ModifiedDate = new DateTime(2024, 10, 10, 10, 46, 42, 475, DateTimeKind.Local).AddTicks(1400)
                        });
                });

            modelBuilder.Entity("PatikaSurvivor.Entities.CompetitorEntity", b =>
                {
                    b.HasOne("PatikaSurvivor.Entities.CategoryEntity", "Category")
                        .WithMany("Competitors")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PatikaSurvivor.Entities.CategoryEntity", b =>
                {
                    b.Navigation("Competitors");
                });
#pragma warning restore 612, 618
        }
    }
}
